name: Sample Github workflow
on: [push]
jobs:
 run-command: 
   runs-on: ubuntu-latest
   steps: 
     - name: echo hello world
       run: eecho "Hello World!"
     - name: multi-line script
       run: |
         node -v
         npm -v